# .github/workflows/deploy.yml
name: Deploy React App to S3

on:
  push:
    branches:
      - main # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build React app
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET }}
          aws-region: ap-south-1 # adjust based on your S3 bucket region

      #- name: Deploy to S3
        #run: aws s3 sync build/ s3://deploy-github-storage --delete

      - name: Set S3 file permissions (optional but recommended)
        run: aws s3 website s3://deploy-github-storage --index-document index.html --error-document index.html
